name: Release
run-name: Releasing ${{ github.ref }}

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: bazel test
        run: |
            bazel test ...

      - name: bazel build :oofork
        run: |
            bazel build --compilation_mode opt :oofork

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bazel-bin/onlyoffice-editor.zip
