name: Checks
run-name: Checking ${{ github.ref }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: make test
        run: |
          make test

      - name: make build
        run: |
          make build
